### PR TITLE
Phpbb 3.2 compatibility + well lots of stuff :)

### PR DESCRIPTION
**Pull request by jdeniau**
Hi,

I finally made a lot of stuff based upon you repository but I can not make several PR for them as they are pretty tied up together:

The main thing is PHPBB 3.2 compatibility

The second main thing is a documentation in the README file 😀 

I added some options or improvements to the bundle (like allow anonymous sessions and taking care of "remember me" functionality).

Finally, I took the liberty of renaming the `connection` configuration key to `entity_manager` as it's an entity manager that is needed and not a connection (which is a dbal notion, but we need a repository in the bundle).

As a final though: I made a PR on your bundle because I started from here but shouldn't we make a PR on phpbb base repository to improve the official bundle ? 

I will open an issue there to see what they think of it, or if they are interesseted too.

Thanks

### CODE REVIEW

**Comment by TeLiXj** [comment]
Great work!!! 2 years waiting advances with this...
I'm working on your code adding roles to user, completing User class, adding compatibility with symfony 3.4/4 and phpBB 3.2.1 and other stuff. I'll create a pull request on your repo when finish.

**Comment by jdeniau** [comment]
Great! Good to hear that the phpbb is active 😀

**Comment by Kwadz** [comment]
@judu, any update about this PR?

**Comment by jdeniau** [comment]
Garbage collecting my opened PRs. This one does probably not work anymore with latest version of phpbb nor latest version of Symfony though.

**Pull request closed without merging**
